name: Node.js Docker CI/CD

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch seluruh riwayat commit (agar git pull berjalan dengan benar)
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Build Docker image for testing
        run: docker build . --file Dockerfile --tag zefanyadiegoforlandi/24001200-km7-zef-mediahandlingandgcp-ch6:test

      - name: Run tests in Docker container
        run: |
          docker run --rm zefanyadiegoforlandi/24001200-km7-zef-mediahandlingandgcp-ch6:test npm test

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image to Docker Hub
        run: |
          docker build . --file Dockerfile --tag zefanyadiegoforlandi/24001200-km7-zef-mediahandlingandgcp-ch6:latest
          docker push zefanyadiegoforlandi/24001200-km7-zef-mediahandlingandgcp-ch6:latest

  deploy:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: SSH to Server and Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/ubuntu/24001200-km7-zef-mediahandlingandgcp-ch6

            git checkout main
            
            sudo git pull origin main

            docker pull zefanyadiegoforlandi/24001200-km7-zef-mediahandlingandgcp-ch6:latest

            docker-compose down
            docker-compose up --build -d

            docker ps -a
